POST http://localhost:4000/toppings
Content-Type: application/json

{
  "toppings": [
    { "name": "Extra Cheese" },
    { "name": "Black Olive" },
    { "name": "Mushroom" },
    { "name": "Pepperoni" },
    { "name": "Olive Oil" },
    { "name": "Onion" },
    { "name": "Sausage" },
    { "name": "Green Pepper" },
    { "name": "Bacon" },
    { "name": "Pineapple" },
    { "name": "Spinach" },
    { "name": "Garlic" },
    { "name": "Crushed Red Pepper" },
    { "name": "Tomato" },
    { "name": "Basil" },
    { "name": "Ham" }
  ]
}
###
